name: FTP Deploy
  # You may pin to the exact commit or the version.
  # uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e
  with:
    # ftp server
    server: 192.169.151.159
    # ftp username
    username: intermedsaude@intermedsaude.online
    # ftp password
    password: SaudeNinho@#
    # Server port to connect to (read your web hosts docs)
    port: # optional
    # protocol to deploy with - ftp, ftps, or ftps-legacy
    protocol: # optional
    # Folder to upload from, must end with trailing slash /
    local-dir: # optional
    # Path to upload to on the server. Must end with trailing slash /
    server-dir: # optional
    # Path and name of the state file - this file is used to track which files have been deployed
    state-name: # optional
    # Prints which modifications will be made with current config options, but doesnt actually make any changes
    dry-run: # optional
    # Deletes ALL contents of server-dir, even items in excluded with exclude argument
    dangerous-clean-slate: # optional
    # An array of glob patterns, these files will not be included in the publish/delete process
    exclude: # optional
    # How verbose should the information be - minimal, standard, or verbose
    log-level: # optional
    # strict or loose
    security: # optional
